//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_Eventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUNOS()
        {
            this.EVENTOS_CURSOS = new HashSet<EVENTOS_CURSOS>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int ALCodigo { get; set; }
        public string ALNome { get; set; }
        public int ALMatricula { get; set; }
        public Nullable<int> ALCodCurso { get; set; }
    
        public virtual CURSOS CURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTOS_CURSOS> EVENTOS_CURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
