//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_Eventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMA
    {
        public int TUCodAluno { get; set; }
        public int TUCodCurso { get; set; }
        public Nullable<int> TUNumeroTurma { get; set; }
        public Nullable<int> TUAno { get; set; }
    
        public virtual ALUNOS ALUNOS { get; set; }
        public virtual CURSOS CURSOS { get; set; }
    }
}
